### ISSUE TITLE
Update Metadata Information

### ISSUE THREAD

**Issue by rpc5102** [EducationShinyAppTeam/Style_Guide#33]
Update the following information on:  
[https://educationshinyappteam.github.io/Style_Guide/coding.html#metadata](https://educationshinyappteam.github.io/Style_Guide/coding.html#metadata) 

Drop:

```r
## App Meta Data----------------------------------------------------------------
APP_TITLE  <<- "Title of the app"
APP_DESCP  <<- paste(
  "Description of the app",
  "use multiple lines to keep the description legible."
)
## End App Meta Data------------------------------------------------------------
```

In favor of:

EducationShinyAppTeam/App\_Template#4

**Comment by rpc5102** [comment]
Resolved in: https://github.com/EducationShinyAppTeam/Style_Guide/commit/342d1bd03cb03df0402f182c02a3adb291525d00.

**Comment by neilhatfield** [comment]
Reopening so that narrative text and examples of the progress EducationShinyAppTeam/App\_Template#4 can be worked into the guide. This would include:

- Formatting long lines for readability in DESCRIPTION
- Entering multiple values for Learning Objectives
- Explanations and guidelines on when to use which roles (aut, cre, ctb)
